### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by AAndromedAA** [AAndromedAA/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Marsichek2** [comment]
'''
He is an avid gamer. This should come as no surprise since Elon Musk even sold a video game called Blastar for $500 when he was merely 12 years old, and once worked at a gaming start-up called Rocket Science. His favorites include Deus Ex, Fallout and BioShock.

He also likes to throw parties. According to Ashlee Vance‘s book, Elon Musk: Tesla, SpaceX and the Quest for a Fantastic Future, Musk’s previous birthdays and office celebrations have included a rented castle in England where the guests played hide-and-seek and a costume party in Venice where he dressed as a knight.

Elon Musk still finds time to binge-watch series on Netflix and HBO. He revealed before that he has seen Silicon Valley, which centers on a fictional tech company, and Black Mirror, which explores humanity‘s relationship to technology

Musk enjoys anime and loved the Makoto Shinkai movie Your Name. He is also a fan of Studio Ghibli movies like Spirited Away and Princess Mononoke. In an interview with Maureen Dowd at The New York Times, Musk said he spent the weekend watching anime (including Death Note and Evangelion) with his girlfriend Grimes.
'''

**Comment by AAndromedAA** [comment]
Well done!
